CREATE TABLE [dbo].[TimeTable] (
    [Id]        INT IDENTITY (1, 1) NOT NULL,
    [Monday]    INT NULL,
    [Tuesday]   INT NULL,
    [Wednesday] INT NULL,
    [Thursday]  INT NULL,
    [Friday]    INT NULL,
    [Saturday]  INT NULL,
    [Sunday]    INT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([Friday]) REFERENCES [dbo].[Time] ([Id]),
    FOREIGN KEY ([Monday]) REFERENCES [dbo].[Time] ([Id]),
    FOREIGN KEY ([Saturday]) REFERENCES [dbo].[Time] ([Id]),
    FOREIGN KEY ([Sunday]) REFERENCES [dbo].[Time] ([Id]),
    FOREIGN KEY ([Thursday]) REFERENCES [dbo].[Time] ([Id]),
    FOREIGN KEY ([Tuesday]) REFERENCES [dbo].[Time] ([Id]),
    FOREIGN KEY ([Wednesday]) REFERENCES [dbo].[Time] ([Id]),
    UNIQUE NONCLUSTERED ([Friday] ASC),
    UNIQUE NONCLUSTERED ([Monday] ASC),
    UNIQUE NONCLUSTERED ([Saturday] ASC),
    UNIQUE NONCLUSTERED ([Sunday] ASC),
    UNIQUE NONCLUSTERED ([Thursday] ASC),
    UNIQUE NONCLUSTERED ([Tuesday] ASC),
    UNIQUE NONCLUSTERED ([Wednesday] ASC)
);

